/** last changed: 2018.12.19 */

module.exports = {
  id: 'ziranma',
  name: '自然码',
  detail: {
    sheng: {
      b: 'B',
      c: 'C',
      d: 'D',
      f: 'F',
      g: 'G',
      h: 'H',
      j: 'J',
      k: 'K',
      l: 'L',
      m: 'M',
      n: 'N',
      p: 'P',
      q: 'Q',
      r: 'R',
      s: 'S',
      t: 'T',
      w: 'W',
      x: 'X',
      y: 'Y',
      z: 'Z',
      ch: 'I',
      sh: 'U',
      zh: 'V'
    },
    yun: {
      a: 'A',
      ai: 'L',
      an: 'J',
      ang: 'H',
      ao: 'K',
      e: 'E',
      ei: 'Z',
      en: 'F',
      eng: 'G',
      i: 'I',
      ia: 'W',
      ian: 'M',
      iang: 'D',
      iao: 'C',
      ie: 'X',
      iong: 'S',
      in: 'N',
      ing: 'Y',
      iu: 'Q',
      o: 'O',
      ong: 'S',
      ou: 'B',
      u: 'U',
      ua: 'W',
      uai: 'Y',
      uan: 'R',
      uang: 'D',
      ue: 'T',
      ui: 'V',
      un: 'P',
      uo: 'O',
      v: 'V',
      ve: 'T'
    },
    other: {
      a: ['A','A'],
      ai: ['A','I'],
      an: ['A','N'],
      ang: ['A','H'],
      ao: ['A','O'],
      e: ['E','E'],
      ei: ['E','I'],
      en: ['E','N'],
      eng: ['E','G'],
      er: ['E','R'],
      o: ['O','O'],
      ou: ['O','U']
    }
  }
}
